apiVersion: v1
kind: Pod
metadata:
  name: tamrin-app-1
  namespace: default
  labels:
    app: tamrin-app
    version: v1
spec:
  terminationGracePeriodSeconds: 30
  containers:
    - name: web
      image: docker.io/library/tamrin-docker:1
      imagePullPolicy: "IfNotPresent"
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      lifecycle:
        preStop:
          exec:
            command: [ "sleep", "30" ]
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3